default:
  golem_name: statsnz.odata.client
  golem_version: 0.0.0.9000
  app_prod: no
  service_prd: https://api.stats.govt.nz/opendata/v1
# TODO: add service url for UAT in some secret way
production:
  app_prod: yes
dev:
  golem_wd: !expr here::here()
